const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const pageNames={home:'首页',about:'关于我们',projects:'项目与作品',news:'最近动态',contact:'联系我们'};
const demoMedia={
 hero:[1,2,3].map(n=>`assets/demo-knowledge-ip/web-pro-cat-v5/hero-0${n}`),
 heroWide:[1,2,3].map(n=>`assets/demo-knowledge-ip/web-pro-cat-v5/hero-wide-0${n}`),
 about:'assets/demo-knowledge-ip/web-pro-cat-v5/about-01',
 projects:[1,2,3,4,5,6].map(n=>`assets/demo-knowledge-ip/web-pro-cat-v5/project-0${n}`),
 news:[1,2,3].map(n=>`assets/demo-knowledge-ip/web-pro-cat-v5/news-0${n}`)
};
const demoProjectTitles=['品牌网站组装器','分格漫画生成器','公众号排版工具','五色配色卡','人物海报试调','编辑式信息长图'];
function mediaStyle(base,desktop='card',mobile=desktop){const active=state?.viewport==='mobile'?mobile:desktop;return `--demo-image:url('${base}-${active}.webp?v=pro-cat-v5');--demo-image-mobile:url('${base}-${mobile}.webp?v=pro-cat-v5')`}
const moduleData={
home:[
{id:'nav',name:'顶部导航',desc:'LOGO 与全站入口',variants:[['standard','标准导航'],['transparent','透明导航'],['floating','悬浮导航'],['hidden','隐藏式导航']]},
{id:'hero',name:'首屏',desc:'第一屏主视觉',variants:[['split','图文分屏轮播'],['center','通屏居中轮播'],['overlay-left','通屏左下轮播'],['carousel','叠层卡片轮播']]},
{id:'about',name:'关于介绍',desc:'人物或公司简介',variants:[['image-left','图文故事'],['stats','宣言＋关键数字'],['icons','浅色图标说明']]},
{id:'works',name:'项目／作品',desc:'精选内容入口',variants:[['tabs','分类卡片矩阵'],['featured','单个重点项目'],['grid','规整组合网格'],['horizontal','通屏横向画廊']]},
{id:'news',name:'最近动态',desc:'新闻与内容更新',variants:[['list','日期标题列表'],['featured','重点动态＋四条列表'],['cards','三列图文卡片'],['timeline','月份时间轴']]},
{id:'contact',name:'联系我们',desc:'联系行动入口',variants:[['minimal','通屏行动句'],['address','联系信息分栏'],['qr','二维码＋联系方式'],['form','咨询表单']]},
{id:'footer',name:'底栏',desc:'版权与辅助导航',variants:[['minimal','极简版权行'],['full','导航栏目版'],['contact','联系二维码版'],['columns','品牌信息四栏']]}
],
about:[{id:'header',name:'页面标题',desc:'关于页开场',variants:[['simple','简洁标题'],['split','标题＋摘要']]},{id:'subnav',name:'二级目录',desc:'左侧切换栏目',variants:[['left','左侧固定目录'],['top','顶部标签目录']]},{id:'content',name:'图文内容',desc:'目录对应内容',variants:[['editorial','标准图文'],['timeline','发展时间线']]}],
projects:[{id:'header',name:'页面标题',desc:'作品页开场',variants:[['simple','简洁标题']]},{id:'filter',name:'项目分类',desc:'分类切换入口',variants:[['pills','圆角标签'],['line','文字标签']]},{id:'list',name:'项目列表',desc:'进入项目详情',variants:[['grid','三列网格'],['featured','重点项目'],['horizontal','横向卡片']]},{id:'detail',name:'详情页外壳',desc:'基础图文详情',variants:[['article','标准图文'],['chapter','章节式图文']]}],
news:[{id:'header',name:'页面标题',desc:'动态页开场',variants:[['simple','简洁标题']]},{id:'list',name:'动态列表',desc:'进入动态详情',variants:[['list','日期列表'],['cards','图片卡片']]},{id:'detail',name:'详情页外壳',desc:'新闻图文详情',variants:[['article','标准图文']]}],
contact:[{id:'header',name:'页面标题',desc:'联系页开场',variants:[['simple','简洁标题']]},{id:'contact',name:'联系结构',desc:'按真实需求选择',variants:[['minimal','极简联系'],['address','地址与电话'],['qr','二维码联系'],['form','咨询表单']]}]
};
const defaults={page:'home',selected:{home:'hero',about:'subnav',projects:'list',news:'list',contact:'contact'},variants:{nav:'standard',hero:'split',about:'image-left',works:'tabs',news:'list',contact:'minimal',footer:'minimal',header:'simple',subnav:'left',content:'editorial',filter:'pills',list:'grid',detail:'article'},theme:{primary:'#28533f',secondary:'#e7e1d4',tertiary:'#d9b56d'},heroHeight:'560',heroMask:'35',openPanel:'module:hero',viewport:'desktop'};
let state=load();
if(state.viewport==='tablet')state.viewport='desktop';
if(state.heroHeight==='640')state.heroHeight='680';
state.homeModules=Array.isArray(state.homeModules)?state.homeModules:moduleData.home.map(m=>({id:m.id,type:m.id,name:m.name,enabled:true,variant:state.variants[m.id]||m.variants[0][0]}));
state.homeModules.forEach(item=>{const def=moduleData.home.find(m=>m.id===item.type);if(!def)return;if(item.type==='about'&&['reverse','tags','full-band'].includes(item.variant))item.variant=item.variant==='reverse'?'image-left':'icons';if(item.type==='news'&&item.variant==='editorial')item.variant='timeline';if(item.type==='hero'&&item.variant==='image-left')item.variant='split';if(!def.variants.some(([id])=>id===item.variant))item.variant=def.variants[0][0]});
state.pageVariants=state.pageVariants||{};
if(!state.demoImagePaletteVersion&&state.theme.primary==='#7057d9'&&state.theme.secondary==='#d8d2ff'&&state.theme.tertiary==='#e9d9b4'){state.theme={primary:'#1f5d45',secondary:'#dce9e1',tertiary:'#e9d8b4'};state.demoImagePaletteVersion=1;localStorage.setItem('site-builder-v07',JSON.stringify(state))}
if(!state.demoArtPortraitVersion&&state.theme.primary==='#1f5d45'&&state.theme.secondary==='#dce9e1'&&state.theme.tertiary==='#e9d8b4'){state.theme={primary:'#273238',secondary:'#dbe2e4',tertiary:'#c7b9ad'};state.demoArtPortraitVersion=1;localStorage.setItem('site-builder-v07',JSON.stringify(state))}
if(!state.demoOwnCatVersion&&state.theme.primary==='#273238'&&state.theme.secondary==='#dbe2e4'&&state.theme.tertiary==='#c7b9ad'){state.theme={primary:'#28533f',secondary:'#e7e1d4',tertiary:'#d9b56d'};state.demoOwnCatVersion=1;localStorage.setItem('site-builder-v07',JSON.stringify(state))}
function homeInstance(id){return state.homeModules.find(m=>m.id===id)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function chosen(m){return state.page==='home'?homeInstance(m.id).variant:(state.pageVariants[state.page]?.[m.id]||state.variants[m.id]||m.variants[0][0])}
function choose(m,id){if(state.page==='home'){homeInstance(m.id).variant=id;if(homeInstance(m.id).type==='nav')state.variants.nav=id;}else{(state.pageVariants[state.page]||={})[m.id]=id}}

if(window.innerWidth<=900)state.viewport='mobile';
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const saved=JSON.parse(localStorage.getItem('site-builder-v07')||'{}');return {...clone(defaults),...saved,selected:{...defaults.selected,...(saved.selected||{})},variants:{...defaults.variants,...(saved.variants||{})},theme:{...defaults.theme,...(saved.theme||{})}}}catch{return clone(defaults)}}
function persist(){localStorage.setItem('site-builder-v07',JSON.stringify(state))}
function currentModules(){return state.page==='home'?state.homeModules.map(i=>({...moduleData.home.find(m=>m.id===i.type),...i})):moduleData[state.page]}
function currentModule(){return currentModules().find(x=>x.id===state.selected[state.page])||currentModules()[0]}
function moduleSettings(m){if((m.type||m.id)==='hero'){const overlays=['center','overlay-left','carousel'].includes(homeInstance('hero')?.variant||state.variants.hero);return `<div class="inline-settings"><label><span>首屏高度</span><select id="heroHeight"><option value="480">紧凑 · 480px</option><option value="560">常规 · 560px</option><option value="680">舒展 · 680px</option><option value="screen">全屏 · 一屏高度</option></select></label>${overlays?`<label><span>背景压暗</span><input id="heroMask" type="range" min="15" max="60" value="${state.heroMask}"><small>让背景与文字保持清楚的明暗关系</small></label>`:''}<p class="research-note">分屏与通屏使用不同裁切；三组背景和文字会一起切换</p></div>`}return `<p class="inline-note">选择一种页面结构，预览区会立即更新并定位到这里</p>`}
function renderModules(){
 const items=currentModules(),home=state.page==='home';$('#panelPageName').textContent=pageNames[state.page]+'模块';
 $('#moduleList').innerHTML=items.map((m,i)=>{const open=state.openPanel===`module:${m.id}`,nav=(m.type||m.id)==='nav';return `<section class="module-accordion ${open?'open':''} ${m.enabled===false?'module-disabled':''}">
 ${home?`<div class="module-tools"><label><input type="checkbox" data-module-enable="${m.id}" ${m.enabled!==false?'checked':''} aria-label="显示${esc(m.name)}">${m.enabled!==false?'显示':'已关闭'}</label>${['about','works','news','contact'].includes(m.type)?`<button type="button" data-duplicate="${m.id}">复制模块</button>`:''}</div>`:''}
 <button class="module-trigger ${m.id===state.selected[state.page]?'active':''}" data-module="${m.id}" aria-expanded="${open}"><span class="module-index">${String(i+1).padStart(2,'0')}</span><span class="module-copy"><b>${esc(m.name)}</b><small>${m.enabled===false?'关闭后不出现在首页，可随时恢复':m.desc}</small></span><span class="module-arrow">›</span></button>
 <div class="module-panel">${home&&!['nav','hero','footer'].includes(m.type)?`<label class="module-name-field">模块名称<input maxlength="30" data-module-name="${m.id}" value="${esc(m.name)}"></label>`:''}
 <div class="variant-head"><span>选择呈现形式</span><small>${m.variants.length} 种</small></div><div class="variant-list text-choices ${nav?'nav-text-choices':''}">${m.variants.map(([id,name],n)=>`<button class="variant-card ${chosen(m)===id?'active':''}" aria-pressed="${chosen(m)===id}" data-module-id="${m.id}" data-variant="${id}"><b>${name}</b></button>`).join('')}</div>${moduleSettings(m)}</div></section>`}).join('');
 $$('.module-trigger').forEach(b=>b.onclick=()=>{const id=b.dataset.module,token=`module:${id}`;state.selected[state.page]=id;state.openPanel=state.openPanel===token?'':token;persist();renderAll();if(state.openPanel)setTimeout(()=>scrollToSection(id),20)});
 $$('[data-variant]').forEach(b=>b.onclick=()=>{const m=currentModules().find(x=>x.id===b.dataset.moduleId);state.selected[state.page]=m.id;choose(m,b.dataset.variant);state.openPanel=`module:${m.id}`;persist();renderAll();setTimeout(()=>scrollToSection(m.id),20)});
 $$('[data-module-enable]').forEach(el=>el.onchange=()=>toggleModule(el.dataset.moduleEnable,el.checked));
 $$('[data-duplicate]').forEach(b=>b.onclick=()=>{const source=homeInstance(b.dataset.duplicate);const copy={...source,id:source.type+'-'+crypto.randomUUID(),name:source.name+' 副本',renamed:true,enabled:true};state.homeModules.splice(state.homeModules.indexOf(source)+1,0,copy);state.selected.home=copy.id;state.openPanel='module:'+copy.id;persist();renderAll();scrollToSection(copy.id)});
 $$('[data-module-name]').forEach(el=>el.onchange=()=>{const item=homeInstance(el.dataset.moduleName);item.name=el.value.trim()||item.name;item.renamed=true;persist();renderAll()});
 const hh=$('#heroHeight');if(hh){hh.value=state.heroHeight;hh.onchange=()=>{state.heroHeight=hh.value;persist();renderPreview();scrollToSection('hero')}}
 const hm=$('#heroMask');if(hm)hm.oninput=()=>{state.heroMask=hm.value;persist();renderPreview();scrollToSection('hero')};renderThemeAccordion()
}
function toggleModule(id,on){const item=homeInstance(id);if(!item)return;item.enabled=on;persist();renderAll();const control=$(`[data-module-enable="${id}"]`);control?.focus({preventScroll:true})}
function renderThemeAccordion(){const open=state.openPanel==='theme',wrap=$('#themeAccordion');wrap.classList.toggle('open',open);$('#themeToggle').setAttribute('aria-expanded',String(open));$('#themeToggle').onclick=()=>{state.openPanel=open?'':'theme';persist();renderAll();if(!open)setTimeout(()=>$('#themeAccordion').scrollIntoView({behavior:'smooth',block:'nearest'}),20)}}
function webNav(){
 const kind=homeInstance('nav')?.variant||'standard';const links=Object.entries(pageNames).filter(([key])=>kind!=='hidden'||key!=='home');
 return `<nav class="web-nav nav-${kind}" data-section="nav" aria-label="网站主导航"><a class="web-logo" href="#home" data-site-page="home">LOGO</a><button type="button" class="web-menu-toggle" aria-expanded="false" aria-controls="webMenu"><span class="menu-lines" aria-hidden="true"><i></i><i></i><i></i></span><span>MENU</span></button><div id="webMenu" class="web-menu">${links.map(([key,label])=>`<a href="#${key}" data-site-page="${key}" class="${state.page===key?'active':''}" ${state.page===key?'aria-current="page"':''}>${label}</a>`).join('')}</div><button class="web-cta" data-site-page="contact">开始沟通</button></nav>`
}
function tag(name){return `<span class="section-tag">${name}</span>`}
function selected(id){return state.selected[state.page]===id?' selected':''}
function heroSection(kind){
 const content=[['好奇小喵，在线施法','实现你的好想法','不必先学会复杂工具。带着你的想法来，回答几个关键问题，把它变成可以继续使用的结果'],['先把问题听明白','再把复杂的办法调好','小喵会继续问一问：你真正想做什么，哪里卡住了，怎样才能更简单地做出来'],['少做几次试错','多带走一个能用的结果','从网站、漫画到内容表达，只留下真正会改变结果的选择，把复杂步骤收进工具里']];
 const fullBleed=kind!=='split',media=fullBleed?demoMedia.heroWide:demoMedia.hero;
 const slides=content.map((x,i)=>`<article class="hero-slide demo-image color-${i+1} ${i===0?'active':''}" style="${mediaStyle(media[i],'desktop','mobile')}" data-slide="${i}"><div class="hero-copy"><span class="eyebrow">WHYMEOW TOOL HOUSE</span><h1>${x[0]}<br>${x[1]}</h1><p>${x[2]}</p><div class="hero-actions"><button class="site-button">看看能帮我做什么</button><button class="site-button alt">认识好奇小喵</button></div></div>${kind==='split'?`<div class="hero-media demo-image" style="${mediaStyle(media[i],'desktop','mobile')}"></div>`:''}${kind==='carousel'?`<div class="hero-side-card"><small>WHYMEOW</small><b>${x[1]}</b></div>`:''}</article>`).join('');
 const height=state.heroHeight==='screen'?(state.viewport==='mobile'?'760px':'calc(100vh - 76px)'):`${state.heroHeight}px`;
 return `<section class="site-section hero hero-carousel hero-${kind}${state.heroHeight==='screen'?' hero-fullscreen':''}${selected('hero')}" data-section="hero" style="height:${height}">${tag('首屏')}<div class="hero-slides">${slides}</div><div class="carousel-ui"><button type="button" data-carousel-prev aria-label="上一张">←</button><div class="carousel-dots">${[0,1,2].map(i=>`<button type="button" data-carousel-dot="${i}" class="${i===0?'active':''}" aria-label="第${i+1}张"></button>`).join('')}</div><button type="button" data-carousel-next aria-label="下一张">→</button></div></section>`
}
function aboutSection(kind){
 if(kind==='stats')return `<section class="site-section about-section about-stats${selected('about')}" data-section="about">${tag('关于介绍')}<div class="section-inner about-manifesto"><span class="eyebrow">ABOUT WHYMEOW</span><h2>工具屋不是用来展示<br>小喵研究了多少东西</h2><p>它想把真正试过、调好、能解决具体问题的办法放在一起，让每个好想法少走一点弯路</p><div class="stat-row"><div><b>01</b><span>先听明白</span></div><div><b>02</b><span>再动手试</span></div><div><b>03</b><span>把结果做出来</span></div></div><button class="site-button">认识好奇小喵</button></div></section>`;
 if(kind==='icons')return `<section class="site-section about-section about-icons${selected('about')}" data-section="about">${tag('关于介绍')}<div class="section-inner"><div class="about-icon-copy"><span class="eyebrow">ABOUT WHYMEOW</span><h2>它的好奇心，总是从<br>别人的问题开始</h2><p>小喵先把问题听明白，再研究、试验和调整，把复杂办法变成更容易使用的工具</p><button class="site-button">阅读完整故事</button></div><div class="about-icon-list">${[['positioning','听清问题'],['organize','理顺步骤'],['expression','交付结果']].map(([icon,text],i)=>`<article><i class="about-icon icon-${icon}" aria-hidden="true"></i><div><b>${text}</b><span>${['先问清楚真正想做什么','只留下会改变结果的选择','把调好的东西交到你手里'][i]}</span></div></article>`).join('')}</div></div></section>`;
 return `<section class="site-section about-section about-story${selected('about')}" data-section="about">${tag('关于介绍')}<div class="section-inner"><div class="about-block"><div class="about-image demo-image" style="${mediaStyle(demoMedia.about,'landscape','portrait')}"></div><div class="about-copy"><span class="eyebrow">ABOUT WHYMEOW</span><h2>它总能注意到<br>别人没有说完的那句话</h2><p>有人有一个好想法，却不知道怎样开始；也有人收藏了很多方法，真正使用时还是要独自试错。小喵想把这些问题听明白，再把复杂的办法调成更容易使用的工具</p><button class="site-button">认识好奇小喵</button></div></div></div></section>`
}
function workCards(count=6){const categories=['brand','content','content','brand','product','product'];return demoProjectTitles.slice(0,count).map((x,i)=>`<article class="work-card" data-work-category="${categories[i]}"><div class="work-image demo-image" style="${mediaStyle(demoMedia.projects[i])}"></div><small>${{brand:'在线工具',content:'内容表达',product:'视觉能力'}[categories[i]]}</small><h3>${x}</h3></article>`).join('')}
function worksSection(kind){
 const head=`<header class="section-head"><h2>今天想实现什么</h2><p>不是再收藏一个方法，而是选择一个能把事情做出来的入口</p><span class="more-link">看看全部工具 →</span></header>`;
 if(kind==='featured')return `<section class="site-section work-section work-featured${selected('works')}" data-section="works">${tag('项目／作品')}<div class="section-inner">${head}<div class="featured-projects">${demoProjectTitles.slice(0,3).map((x,i)=>`<article class="featured-slide ${i===0?'active':''}" data-work-slide="${i}"><div class="featured-image demo-image" style="${mediaStyle(demoMedia.projects[i],'wide')}"></div><div><small>FEATURED TOOL</small><h3>${x}</h3><p>${['先看见完整网站效果，再带走结构与样式','把角色和故事变成可观看、可继续修改的漫画','从标题到结尾，整理出稳定的公众号表达方式'][i]}</p></div></article>`).join('')}<div class="rail-controls"><button type="button" data-work-prev aria-label="上一个项目">←</button><span data-work-count>01 / 03</span><button type="button" data-work-next aria-label="下一个项目">→</button></div></div></div></section>`;
 if(kind==='grid')return `<section class="site-section work-section work-mosaic${selected('works')}" data-section="works">${tag('项目／作品')}<div class="section-inner">${head}<div class="mosaic-grid">${demoProjectTitles.slice(0,4).map((x,i)=>`<article class="mosaic-item"><div class="work-image demo-image" style="${mediaStyle(demoMedia.projects[i],'wide')}"></div><div class="mosaic-meta"><h3>${x}</h3><span>${i%2?'内容表达':'在线工具'} · 样张</span></div></article>`).join('')}</div></div></section>`;
 if(kind==='horizontal')return `<section class="site-section work-section work-horizontal${selected('works')}" data-section="works">${tag('项目／作品')}<div class="wide-section-head">${head}<div class="rail-controls"><button type="button" data-rail-prev aria-label="向前浏览">←</button><button type="button" data-rail-next aria-label="向后浏览">→</button></div></div><div class="horizontal-window"><div class="horizontal-track">${demoProjectTitles.map((x,i)=>`<article class="work-card horizontal-card demo-image" style="${mediaStyle(demoMedia.projects[i],'wide')}"><span>0${i+1}</span><h3>${x}</h3><small>OPEN TOOL ↗</small></article>`).join('')}</div></div></section>`;
 return `<section class="site-section work-section work-tabs-layout${selected('works')}" data-section="works">${tag('项目／作品')}<div class="section-inner">${head}<div class="work-tabs"><button class="active" data-work-filter="all">全部</button><button data-work-filter="brand">在线工具</button><button data-work-filter="content">内容表达</button><button data-work-filter="product">视觉能力</button></div><div class="work-grid">${workCards()}</div></div></section>`
}
function newsSection(kind){
 const items=['为什么工具屋先问问题，再开始制作','一套网站样张是怎样被慢慢调顺的','把复杂选择收起来以后，用户还需要什么','最近在研究的图标、图片与页面节奏'];
 if(kind==='featured')return `<section class="site-section news-section news-featured${selected('news')}" data-section="news">${tag('最近动态')}<div class="section-inner"><header class="section-head"><h2>小喵最近在研究什么</h2><span class="more-link">查看全部 →</span></header><div class="news-feature-layout"><article class="news-lead"><div class="news-color demo-image" style="${mediaStyle(demoMedia.news[0],'wide')}"></div><time>2026.10.08</time><h3>本月重点：让一套网站样张真正看得清、选得准、带得走</h3></article><div class="news-side">${items.map((x,i)=>`<article><time>10.0${8-i}</time><h3>${x}</h3><span>→</span></article>`).join('')}</div></div></div></section>`;
 if(kind==='cards')return `<section class="site-section news-section news-cards${selected('news')}" data-section="news">${tag('最近动态')}<div class="section-inner"><header class="section-head"><h2>最近动态</h2><span class="more-link">查看全部 →</span></header><div class="news-card-grid">${items.slice(0,3).map((x,i)=>`<article><div class="news-color demo-image" style="${mediaStyle(demoMedia.news[i])}"></div><time>2026.10.0${7-i}</time><h3>${x}</h3><span>阅读 →</span></article>`).join('')}</div></div></section>`;
 if(kind==='timeline')return `<section class="site-section news-section news-timeline${selected('news')}" data-section="news">${tag('最近动态')}<div class="section-inner"><header class="section-head"><h2>工具屋研究手记</h2><p>记录问题、试验、调整和真正可用的结果</p><span class="more-link">查看全部 →</span></header><div class="timeline-grid">${[['OCT','网站样张与图片节奏'],['SEP','内容工具的输入与输出'],['AUG','一个真实问题的拆解'],['JUL','把复杂步骤变简单']].map(([m,x],i)=>`<article><b>${m}</b><i class="color-${i%3+1}"></i><h3>${x}</h3><span>2026 · ${String(10-i).padStart(2,'0')}</span></article>`).join('')}</div></div></section>`;
 return `<section class="site-section news-section news-simple${selected('news')}" data-section="news">${tag('最近动态')}<div class="section-inner"><header class="section-head"><h2>小喵最近在研究什么</h2><p>记录一个问题怎样被听见、理顺、试验，再变成可用的工具</p><span class="more-link">查看全部 →</span></header><div class="news-list">${items.map((x,i)=>`<article class="news-item"><time>2026.10.0${8-i}</time><h3>${x}</h3><span>→</span></article>`).join('')}</div></div></section>`
}
function contactSection(kind){
 if(kind==='address')return `<section class="site-section contact-section contact-address${selected('contact')}" data-section="contact">${tag('联系我们')}<div class="section-inner"><div><span class="eyebrow">CONTACT</span><h2>先告诉小喵<br>你想做什么</h2></div><div class="contact-columns"><div><small>EMAIL</small><b>hello@example.com</b></div><div><small>WAY</small><b>在线 / 可远程协作</b></div><div><small>QUESTION</small><b>你被哪一步卡住了？</b></div></div></div></section>`;
 if(kind==='qr')return `<section class="site-section contact-section contact-qr${selected('contact')}" data-section="contact">${tag('联系我们')}<div class="section-inner"><div><span class="eyebrow">CONTACT</span><h2>扫码建立联系<br>或者发送邮件</h2><p>二维码和真实联系方式将在生成后替换</p></div><div class="qr-contact"><div class="qr-box color-2">QR</div><div><b>商务合作</b><span>hello@example.com</span><b>内容交流</b><span>WECHAT ID</span></div></div></div></section>`;
 if(kind==='form')return `<section class="site-section contact-section contact-form${selected('contact')}" data-section="contact">${tag('联系我们')}<div class="section-inner"><div><span class="eyebrow">CONTACT</span><h2>告诉我们你的需求</h2><p>这里只展示表单排版，生成后再由 AI 接入真实收集方式</p></div><form class="form-shell"><label>你的称呼<input value="姓名 / 品牌名" readonly></label><label>联系方式<input value="邮箱 / 微信" readonly></label><label>想聊的事情<textarea readonly>请简单描述你的需求</textarea></label><button type="button" class="site-button">提交需求</button></form></div></section>`;
 return `<section class="site-section contact-section contact-minimal${selected('contact')}" data-section="contact">${tag('联系我们')}<div class="contact-line"><span class="eyebrow">CONTACT</span><h2>带着你的好想法来吧<br>我们一起把它做出来</h2><button class="site-button">告诉小喵　→</button></div></section>`
}
function footerSection(kind){
 if(kind==='full')return `<footer class="site-section footer footer-full${selected('footer')}" data-section="footer">${tag('底栏')}<b>LOGO</b><div><strong>网站</strong><span>关于我们</span><span>项目与作品</span><span>最近动态</span></div><div><strong>联系</strong><span>商务合作</span><span>内容交流</span><span>城市 / 远程</span></div><small>© 2026</small></footer>`;
 if(kind==='contact')return `<footer class="site-section footer footer-contact${selected('footer')}" data-section="footer">${tag('底栏')}<div><b>LOGO</b><p>好奇小喵，在线施法，实现你的好想法</p></div><div class="footer-qr color-2">QR</div><div><strong>保持联系</strong><span>hello@example.com</span><span>WECHAT ID</span></div><small>© 2026</small></footer>`;
 if(kind==='columns')return `<footer class="site-section footer footer-columns${selected('footer')}" data-section="footer">${tag('底栏')}<div><b>LOGO</b><p>好奇小喵工具屋</p></div><div><strong>工具</strong><span>网站组装</span><span>分格漫画</span></div><div><strong>内容</strong><span>研究手记</span><span>使用说明</span></div><div><strong>联系</strong><span>hello@example.com</span><span>在线 / 远程</span></div></footer>`;
 return `<footer class="site-section footer footer-minimal${selected('footer')}" data-section="footer">${tag('底栏')}<b>LOGO</b><span>© 2026　All rights reserved</span></footer>`
}
function homeTemplate(v){return `${webNav()}${heroSection(v.hero)}${aboutSection(v.about)}${worksSection(v.works)}${newsSection(v.news)}${contactSection(v.contact)}${footerSection(v.footer)}`}
function homeHTML(){
 return state.homeModules.filter(i=>i.enabled).map(item=>{const t=document.createElement('template');const variants={...state.variants,...Object.fromEntries(state.homeModules.filter(i=>i.id===i.type).map(i=>[i.type,i.variant])),[item.type]:item.variant};t.innerHTML=homeTemplate(variants);const el=t.content.querySelector(`[data-section="${item.type}"]`);if(!el)return '';el.dataset.section=item.id;el.dataset.moduleType=item.type;el.classList.toggle('selected',state.selected.home===item.id);const tag=el.querySelector('.section-tag');if(tag)tag.textContent=item.name;if(item.renamed){const h=el.querySelector('h2');if(h)h.textContent=item.name;}return el.outerHTML}).join('')||'<div class="empty-home">首页模块已关闭，可在左侧重新开启</div>'
}
function navigateSite(page){if(!pageNames[page])return;state.page=page;state.openPanel='module:'+state.selected[page];persist();renderAll();$('#canvasSpace').scrollTop=0;closeDrawers()}
let previewTimers=[];
function clearPreviewTimers(){previewTimers.forEach(clearInterval);previewTimers=[]}
function autoplay(fn,delay){if(!matchMedia('(prefers-reduced-motion: reduce)').matches)previewTimers.push(setInterval(fn,delay))}
function wirePreview(){
 const p=$('#sitePreview');p.dataset.navStyle=homeInstance('nav')?.variant||'standard';
 p.classList.toggle('has-top-nav',!!p.querySelector('.web-nav'));
 p.querySelectorAll('[data-site-page]').forEach(a=>a.onclick=e=>{e.preventDefault();navigateSite(a.dataset.sitePage)});
 const nav=p.querySelector('.web-nav'),toggle=p.querySelector('.web-menu-toggle');
 const menu=p.querySelector('.web-menu');
 function setOpen(on){nav?.classList.toggle('menu-open',on);toggle?.setAttribute('aria-expanded',String(on));}
 if(toggle){toggle.onclick=()=>setOpen(toggle.getAttribute('aria-expanded')!=='true');nav.onkeydown=e=>{if(e.key==='Escape'){setOpen(false);toggle.focus();}};nav.onfocusout=e=>{if(!nav.contains(e.relatedTarget))setOpen(false)};}p.onclick=e=>{if(nav&&!nav.contains(e.target))setOpen(false)};
  if(state.page==='home'){
  p.querySelectorAll('[data-section]').forEach(el=>{const item=homeInstance(el.dataset.section);if(!item)return;
   if(item.type!=='nav'){const b=document.createElement('button');b.type='button';b.className='section-disable';b.setAttribute('aria-label','关闭'+item.name);b.textContent='开 / 关闭模块';b.onclick=()=>toggleModule(item.id,false);el.prepend(b)}
   const target={about:'about',works:'projects',news:'news',contact:'contact'}[item.type];if(target)el.querySelectorAll('.more-link,.about-copy .site-button').forEach(a=>{a.tabIndex=0;a.setAttribute('role','link');a.onclick=()=>navigateSite(target);a.onkeydown=e=>{if(e.key==='Enter')navigateSite(target)}})
  });
   p.querySelectorAll('.hero-actions button').forEach((b,i)=>b.onclick=()=>navigateSite(i?'about':'projects'));
   p.querySelectorAll('.work-tabs-layout').forEach(root=>{const buttons=$$('[data-work-filter]',root),cards=$$('[data-work-category]',root);buttons.forEach(button=>button.onclick=()=>{const filter=button.dataset.workFilter;buttons.forEach(x=>x.classList.toggle('active',x===button));cards.forEach(card=>{card.hidden=filter!=='all'&&card.dataset.workCategory!==filter})})});
   p.querySelectorAll('.hero-carousel').forEach(root=>{const slides=$$('.hero-slide',root),dots=$$('[data-carousel-dot]',root);let index=0;const show=n=>{index=(n+slides.length)%slides.length;slides.forEach((s,i)=>s.classList.toggle('active',i===index));dots.forEach((d,i)=>d.classList.toggle('active',i===index))};$('[data-carousel-prev]',root).onclick=()=>show(index-1);$('[data-carousel-next]',root).onclick=()=>show(index+1);dots.forEach(d=>d.onclick=()=>show(Number(d.dataset.carouselDot)));autoplay(()=>show(index+1),4600)});
   p.querySelectorAll('.work-featured').forEach(root=>{const slides=$$('.featured-slide',root),count=$('[data-work-count]',root);let index=0;const show=n=>{index=(n+slides.length)%slides.length;slides.forEach((s,i)=>s.classList.toggle('active',i===index));count.textContent=`0${index+1} / 0${slides.length}`};$('[data-work-prev]',root).onclick=()=>show(index-1);$('[data-work-next]',root).onclick=()=>show(index+1);autoplay(()=>show(index+1),5200)});
   p.querySelectorAll('.work-horizontal').forEach(root=>{const track=$('.horizontal-track',root),cards=$$('.work-card',root);let index=0;const max=Math.max(0,cards.length-(state.viewport==='mobile'?1:3));const show=n=>{index=Math.max(0,Math.min(max,n));track.style.transform=`translateX(-${index*(state.viewport==='mobile'?86:34)}%)`};$('[data-rail-prev]',root).onclick=()=>show(index-1);$('[data-rail-next]',root).onclick=()=>show(index>=max?0:index+1);autoplay(()=>show(index>=max?0:index+1),4300)});
  }
}
function aboutHTML(){return `${webNav()}<main class="inner-page"><header class="inner-hero site-section${selected('header')}" data-section="header">${tag('页面标题')}<span class="eyebrow">ABOUT WHYMEOW</span><h1>关于好奇小喵</h1><p>它的好奇心，总是从别人的问题开始。它先听、再问、再动手把复杂的办法调简单</p></header><div class="about-page-body site-section${selected('subnav')}" data-section="subnav">${tag('二级目录')}<nav class="subnav"><button class="active">它是谁</button><button>为什么做工具屋</button><button>怎样帮忙</button><button>工具上架原则</button></nav><article class="inner-copy"><h2>它总能注意到别人没有说完的那句话</h2><p>有人有一个好想法，却不知道怎样开始；有人被复杂步骤卡住；也有人收藏了许多方法，真正使用时仍要独自试错。</p><p>小喵会坐下来听，把混在一起的问题一点点理清楚，再去寻找和研究解决办法。</p><div class="inner-image demo-image" style="${mediaStyle(demoMedia.about,'landscape','portrait')}"></div></article></div></main>`}
function projectsHTML(type='projects'){const isNews=type==='news',title=isNews?'小喵研究手记':'工具架',media=isNews?demoMedia.news:demoMedia.projects;return `${webNav()}<main class="inner-page"><header class="inner-hero site-section${selected('header')}" data-section="header">${tag('页面标题')}<span class="eyebrow">${isNews?'WHYMEOW NOTES':'TOOLS & RESULTS'}</span><h1>${title}</h1><p>${isNews?'记录一个问题怎样变成更容易使用的办法':'按想实现的事情浏览工具，选择一个合适的入口'}</p></header><section class="project-list site-section${selected('list')}" data-section="list">${tag(isNews?'动态列表':'工具列表')}${demoProjectTitles.map((x,i)=>`<article class="project-tile"><i class="demo-image" style="${mediaStyle(media[i%media.length])}"></i><h3>${isNews?['问题从哪里开始','怎样减少无效选择','网站样张的页面节奏','工具如何被验证','为什么不让用户从头学','一次新的研究'][i]:x}</h3><p>${isNews?'来自工具屋的研究、试验和调整记录':'带着一个具体想法来，完成少量必要选择，再把结果带走'}</p></article>`).join('')}</section></main>`}
function contactHTML(){return `${webNav()}<main class="inner-page"><header class="inner-hero site-section${selected('header')}" data-section="header">${tag('页面标题')}<span class="eyebrow">CONTACT</span><h1>联系我们</h1><p>根据真实需求选择极简联系、地址信息、二维码或咨询表单</p></header><section class="site-section contact-section ${state.pageVariants.contact?.contact||state.variants.contact}${selected('contact')}" data-section="contact">${tag('联系结构')}<div class="section-inner"><div><h2>让我们开始一次<br>具体的交流</h2><p>这里的真实信息将在生成后填入</p></div><div class="contact-info"><div>邮箱　hello@example.com</div><div>电话　000-0000-0000</div><div>地址　城市 / 区域</div>${state.variants.contact==='qr'?'<div class="qr-box">QR CODE</div>':''}</div></div></section></main>`}
const virtualWidths={desktop:1920,mobile:390};let currentScale=1;
function updateScale(){const canvas=$('#canvasSpace'),shell=$('#scaleShell'),frame=$('#siteFrame');if(!canvas||!shell||!frame)return;const virtualWidth=virtualWidths[state.viewport]||1920,available=Math.max(280,canvas.clientWidth-36);currentScale=Math.min(1,available/virtualWidth);frame.style.width=virtualWidth+'px';frame.style.transform=`scale(${currentScale})`;frame.className='site-frame '+state.viewport;shell.style.width=(virtualWidth*currentScale)+'px';shell.style.height=(frame.scrollHeight*currentScale)+'px'}
function renderPreview(){clearPreviewTimers();const html=state.page==='home'?homeHTML():state.page==='about'?aboutHTML():state.page==='projects'?projectsHTML():state.page==='news'?projectsHTML('news'):contactHTML();const p=$('#sitePreview');p.style.setProperty('--brand',state.theme.primary);p.style.setProperty('--brand2',state.theme.secondary);p.style.setProperty('--brand3',state.theme.tertiary);p.style.setProperty('--hero-mask',String(Number(state.heroMask)/100));p.innerHTML=html;wirePreview();requestAnimationFrame(updateScale)}
const palettes=[['#28533f','#e7e1d4','#d9b56d'],['#153f38','#b9d8cc','#ead7bb'],['#a84832','#edc4b8','#f0dfb2'],['#1f3d70','#b8cae8','#d8d0ea'],['#202124','#d4d4d0','#c5b08b'],['#71344f','#e6bfd0','#d8d2ef']];
function renderTheme(){for(const [id,key] of [['primary','primary'],['secondary','secondary'],['tertiary','tertiary']]){const input=$('#'+id+'Color'),value=$('#'+id+'Value');input.value=state.theme[key];value.textContent=state.theme[key].toUpperCase();input.oninput=()=>{state.theme[key]=input.value;value.textContent=input.value.toUpperCase();persist();renderPreview()}}$('#paletteList').innerHTML=palettes.map((p,i)=>`<button class="palette" data-palette="${i}" aria-label="配色 ${i+1}">${p.map(c=>`<i style="background:${c}"></i>`).join('')}</button>`).join('');$$('[data-palette]').forEach(b=>b.onclick=()=>{const p=palettes[Number(b.dataset.palette)];state.theme={primary:p[0],secondary:p[1],tertiary:p[2]};persist();renderAll();toast('已应用整站配色')})}
function renderAll(){$$('.page-tab').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));$('#stageTitle').textContent=pageNames[state.page]+'完整预览';renderModules();renderPreview();renderTheme()}
function scrollToSection(id){const el=$(`[data-section="${id}"]`,$('#sitePreview')),canvas=$('#canvasSpace');if(el&&canvas)canvas.scrollTo({top:Math.max(0,el.offsetTop*currentScale-28),behavior:'smooth'})}
$$('.page-tab').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.openPanel=`module:${state.selected[state.page]}`;persist();renderAll();closeDrawers()});
$$('.viewport').forEach(b=>b.onclick=()=>{$$('.viewport').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.viewport=b.dataset.view;persist();renderPreview()});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('#saveBtn').onclick=()=>{persist();toast('项目已保存在当前浏览器')};
$('#previewBtn').onclick=()=>{document.body.classList.toggle('preview-mode');$('#previewBtn').textContent=document.body.classList.contains('preview-mode')?'返回编辑':'整页预览'};
function openModal(id){$('#'+id).showModal()}$$('[data-modal-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.modalClose).close());$('#helpBtn').onclick=()=>openModal('helpModal');$('#generateBtn').onclick=()=>openModal('generateModal');
$('#confirmGenerate').onclick=()=>{const payload={type:'website-effect-plan',version:'0.8-instances',generated_at:new Date().toISOString(),pages:Object.fromEntries(Object.entries(moduleData).map(([k,v])=>[k,k==='home'?state.homeModules.map((m,index)=>({instance_id:m.id,module:m.type,name:m.name,enabled:m.enabled,order:index,variant:m.variant})):v.map(m=>({instance_id:k+'-'+m.id,module:m.id,variant:state.pageVariants[k]?.[m.id]||state.variants[m.id]||m.variants[0][0]}))])),theme:state.theme,hero:{height:state.heroHeight==='screen'?'screen':Number(state.heroHeight),mask:Number(state.heroMask)},placeholder_policy:'solid-color',content_policy:'Fill real content after generation with the user AI. Disabled home sections do not delete inner pages.'};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='网站方案配置.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);$('#generateModal').close();toast('网站方案已生成并下载')};
function closeDrawers(){$$('.side-panel').forEach(x=>x.classList.remove('drawer-open'));$('#drawerBackdrop').classList.remove('show')}$('#moduleDrawerBtn').onclick=()=>{$('#modulesPanel').classList.add('drawer-open');$('#drawerBackdrop').classList.add('show')};$$('[data-close]').forEach(b=>b.onclick=closeDrawers);$('#drawerBackdrop').onclick=closeDrawers;
new ResizeObserver(updateScale).observe($('#canvasSpace'));new ResizeObserver(updateScale).observe($('#sitePreview'));$$('.viewport').forEach(b=>b.classList.toggle('active',b.dataset.view===state.viewport));renderAll();


