const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const styleImages={p01:'assets/comic/preview-panels.png',p02:'assets/comic/p02.png',p03:'assets/comic/p03.png',p04:'assets/comic/p04.png',p05:'assets/comic/p05.png',p06:'assets/comic/p06.png'};
const state={style:'p01',styleName:'扁平编辑',title:'为什么结果总在漂移？',content:$('#contentInput').value,identity:false,colors:{primary:'#315cd6',accent:'#ef5a3c',paper:'#f6f2e9'},font:'editorial',route:'解释型内容'};
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function analyze(text){if(/后来|然后|有一天|终于|故事|经历/.test(text))return'故事型内容';if(/步骤|首先|其次|最后|流程|第[一二三四五六]/.test(text))return'流程型内容';if(/之前|之后|对比|不同|变化|前后/.test(text))return'对比型内容';if(/[“”「」]|问：|答：|为什么.*\?/.test(text))return'对话型内容';return'解释型内容'}
function renderTitle(value){const title=(value||'未命名漫画').trim();const key=title.includes('漂移')?'漂移':title.includes('结果')?'结果':'';$('#previewTitle').innerHTML=key?escapeHtml(title).replace(escapeHtml(key),'<em>'+escapeHtml(key)+'</em>'):escapeHtml(title);requestAnimationFrame(fitComic)}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function update(){document.documentElement.style.setProperty('--primary',state.colors.primary);document.documentElement.style.setProperty('--accent',state.colors.accent);document.documentElement.style.setProperty('--comic-paper',state.colors.paper);document.body.classList.remove('font-editorial','font-diary','font-news','font-bold');document.body.classList.add(`font-${state.font}`);$('#previewImage').src=styleImages[state.style];$('#styleState').textContent=`${state.styleName} · ${state.identity?'个人形象设定已记录':'通用人物'} · 校准中`;$('#routeStatus').textContent=state.route;renderTitle(state.title)}
$$('.style-card').forEach(card=>card.onclick=()=>{$$('.style-card').forEach(x=>x.classList.remove('active'));card.classList.add('active');state.style=card.dataset.style;state.styleName=card.dataset.name;update()});
$('#titleInput').addEventListener('input',e=>{state.title=e.target.value;renderTitle(state.title)});$('#contentInput').addEventListener('input',e=>state.content=e.target.value);
$('#analyzeBtn').onclick=()=>{state.content=$('#contentInput').value;state.title=$('#titleInput').value;state.route=analyze(state.content);update();toast(`已判断为${state.route}，仅更新类型建议，未生成新分镜`)};$('#refreshRoute').onclick=$('#analyzeBtn').onclick;
$('#identityToggle').onchange=e=>{state.identity=e.target.checked;$('#identityFields').hidden=!state.identity;update()};$('#portraitUpload').onchange=e=>{$('#uploadState').textContent=e.target.files[0]?.name||'仅用于当前项目';if(e.target.files[0])toast('已选择会话参考照片；刷新与导出不保留')};
$('#primaryColor').oninput=e=>{state.colors.primary=e.target.value;update()};$('#accentColor').oninput=e=>{state.colors.accent=e.target.value;update()};$('#paperColor').oninput=e=>{state.colors.paper=e.target.value;update()};$('#fontPair').onchange=e=>{state.font=e.target.value;update()};
function projectData(){return{schema:'mengyu-comic-calibration/v0.1',savedAt:new Date().toISOString(),status:'unvalidated-draft',sampleIsReusableRule:false,capabilities:{imageGeneration:false,skillPackage:false},content:{title:$('#titleInput').value,source:$('#contentInput').value,relation:state.route},identity:{enabled:state.identity,name:$('#characterName').value,traits:$('#characterTraits').value,photoStored:false,mode:state.identity?'personal':'style-only'},style:{id:state.style,name:state.styleName,colors:state.colors,fontPair:state.font},routing:{layout:'auto-from-content',newContentEachRun:true,outputProfiles:['xiaohongshu','wechat-image-text','moments-9x16']},nextGate:'character-continuity-and-second-content-regression'}}
function download(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#saveProject').onclick=()=>{localStorage.setItem('mengyu-comic-project-v01',JSON.stringify(projectData()));toast('项目已保存在当前浏览器')};$('#exportProfile').onclick=()=>{download('我的漫画风格_校准配置.json',projectData());toast('草稿配置已下载')};$('#runRegression').onclick=()=>{const d=projectData();d.status='awaiting-regression';localStorage.setItem('mengyu-comic-project-v01',JSON.stringify(d));toast('已记录为待回归版本')};
try{const saved=JSON.parse(localStorage.getItem('mengyu-comic-project-v01')||'null');if(saved){state.style=saved.style?.id||state.style;state.styleName=saved.style?.name||state.styleName;state.colors={...state.colors,...saved.style?.colors};state.font=saved.style?.fontPair||state.font;state.route=saved.content?.relation||state.route;state.title=saved.content?.title||state.title;state.content=saved.content?.source||state.content;state.identity=!!saved.identity?.enabled;$('#titleInput').value=state.title;$('#contentInput').value=state.content;$('#identityToggle').checked=state.identity;$('#identityFields').hidden=!state.identity;$('#characterName').value=saved.identity?.name||'';$('#characterTraits').value=saved.identity?.traits||'';$('#primaryColor').value=state.colors.primary;$('#accentColor').value=state.colors.accent;$('#paperColor').value=state.colors.paper;$('#fontPair').value=state.font;$$('.style-card').forEach(x=>x.classList.toggle('active',x.dataset.style===state.style))}}catch{}
update();

// Four steps, two identity paths. Existing form nodes are moved, never duplicated.
const panel=$('.style-panel'),heading=$('.panel-heading'),grid=$('#styleGrid');
const sections=$$('.inspector .control-section');
heading.remove();panel.innerHTML='<div class="flow-intro"><h1>做一套自己的漫画风格</h1><p>按下面四步设置，右侧随时查看参考。</p></div>';
function addStep(id,num,title,summary){const d=document.createElement('details');d.className='flow-step';d.id='flow-'+id;d.open=true;const s=document.createElement('summary');s.innerHTML='<span class="step-number">'+num+'</span><span><b>'+title+'</b><small>'+summary+'</small></span>';d.append(s);const body=document.createElement('div');body.className='step-body';d.append(body);panel.append(d);return body}
const roleBody=addStep('role','01','需要固定角色吗？','只定风格，或以自己的形象长期创作');
sections.forEach(s=>s.querySelector('.section-title')?.remove());
const choices=document.createElement('fieldset');choices.className='role-choices';choices.innerHTML='<legend class="sr-only">角色使用方式</legend><label><input type="radio" name="roleMode" value="style"><span><b>只定风格</b><small>人物和场景随内容安排</small></span></label><label><input type="radio" name="roleMode" value="personal"><span><b>固定我的形象</b><small>让同一个我出现在不同内容里</small></span></label>';roleBody.append(choices,sections[1]);
$('.toggle-row',sections[1]).hidden=true;
function syncRole(){const mode=state.identity?'personal':'style';$$('[name=roleMode]').forEach(r=>r.checked=r.value===mode)}
$$('[name=roleMode]').forEach(r=>r.onchange=()=>{const toggle=$('#identityToggle');toggle.checked=r.value==='personal';toggle.dispatchEvent(new Event('change'));syncRole()});syncRole();
const styleBody=addStep('style','02','选喜欢的画风','六种参考，点击切换');styleBody.append(grid);$$('.style-card small').forEach(n=>n.remove());
const trialBody=addStep('trial','03','试一张，再调整','测试内容、颜色和字体放在一起');trialBody.append(sections[0],sections[2]);
const generate=document.createElement('button');generate.id='generateSample';generate.className='wide-button';generate.disabled=true;generate.textContent='生成我的样稿 · 尚未接入';trialBody.append(generate);
const hint=document.createElement('p');hint.className='hint';hint.textContent='右侧仍是已有参考，不是用你的内容或照片生成的新图。标题与底色可以即时试调；人物、画风重绘需要生图服务。';trialBody.append(hint);
const exportBody=addStep('export','04','满意后，带走','带走规则，不锁死这一次的测试内容');exportBody.append(sections[3]);
const skillButton=document.createElement('button');skillButton.className='wide-button';skillButton.disabled=true;skillButton.textContent='生成 Skill 包 · 待接入';exportBody.append(skillButton);
const exportButton=document.createElement('button');exportButton.id='downloadDraft';exportButton.className='wide-button secondary';exportButton.textContent='下载草稿配置';exportButton.onclick=()=>$('#exportProfile').click();exportBody.append(exportButton);
var previewZoom=false;
function fitComic(){const canvas=$('#comicCanvas'),wrap=$('.canvas-wrap'),stage=$('.preview-stage');if(!canvas||!wrap)return;canvas.style.zoom=1;stage?.classList.toggle('is-zoomed',previewZoom);const scale=previewZoom?Math.min(1.4,Math.max(.2,(wrap.clientWidth-40)/500)):Math.max(.15,Math.min(1,(wrap.clientWidth-40)/500,(wrap.clientHeight-40)/canvas.scrollHeight));canvas.style.zoom=scale}
$('#fitPreview').onclick=()=>{previewZoom=false;fitComic()};$('#zoomPreview').onclick=()=>{previewZoom=true;fitComic()};$('#previewImage').addEventListener('load',fitComic);new ResizeObserver(()=>requestAnimationFrame(fitComic)).observe($('.canvas-wrap'));document.fonts.ready.then(fitComic);
